name: Repository Dispatch
on:
  repository_dispatch:
    types: [update]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ github.event.client_payload.version }}
      - name: Create Pull Request
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: GitHub OpenAPI specifications changed
          body: >
            There is a new release of GitHub OpenAPI specification. Verify that there are no breaking changes
          branch: openapi-update-${{ github.event.client_payload.version }}
          commit-message: WIP octokit/openapi updated
